@ClipboardSyncServer_HostAddress = http://localhost:5292



POST http://localhost:5292/api/clipboard
Content-Type: application/json
Accept: application/json
{
  "Device": "pc",
  "Data": "Sample clipboard data",
  "DeviceName": "My PC"
}
###
### Get Clipboard Data
GET http://localhost:5292/api/clipboard?device=pc
Accept: application/json

